from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from .schemas import utc_timestamp

SKILL_ROOT = Path(".agents") / "skills"
REGISTRY_JSON = "skill_registry.json"
REGISTRY_MD = "SKILL_REGISTRY.md"


def refresh_skill_registry(
    workspace: str | Path,
    *,
    repo_root: str | Path = ".",
) -> dict[str, Any]:
    root = Path(repo_root)
    skill_root = root / SKILL_ROOT
    skills = [
        _skill_entry(path, root)
        for path in sorted(skill_root.rglob("SKILL.md"), key=lambda item: item.as_posix())
        if not any(part.startswith(".") and part != ".agents" for part in path.parts)
    ]
    skills.sort(key=lambda item: item["name"])

    registry = {
        "generated_at": utc_timestamp(),
        "skill_root": SKILL_ROOT.as_posix(),
        "skills": skills,
    }

    project = Path(workspace) / "project"
    project.mkdir(parents=True, exist_ok=True)
    (project / REGISTRY_JSON).write_text(
        json.dumps(registry, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (project / REGISTRY_MD).write_text(_registry_markdown(registry), encoding="utf-8")
    return registry


def suggest_skills(
    workspace: str | Path,
    query: str,
    *,
    repo_root: str | Path = ".",
    refresh: bool = False,
    limit: int = 5,
) -> list[dict[str, Any]]:
    registry = (
        refresh_skill_registry(workspace, repo_root=repo_root)
        if refresh
        else load_skill_registry(workspace)
    )
    query_tokens = _tokens(query)
    if not query_tokens:
        return []

    matches = []
    for skill in registry.get("skills", []):
        score = _score_skill(skill, query, query_tokens)
        if score <= 0:
            continue
        match = dict(skill)
        match["score"] = score
        matches.append(match)

    matches.sort(key=lambda item: (-item["score"], item["name"]))
    return matches[:limit]


def load_skill_registry(workspace: str | Path) -> dict[str, Any]:
    path = Path(workspace) / "project" / REGISTRY_JSON
    if not path.exists():
        return {"skill_root": SKILL_ROOT.as_posix(), "skills": []}
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        return {"skill_root": SKILL_ROOT.as_posix(), "skills": []}
    data.setdefault("skills", [])
    data.setdefault("skill_root", SKILL_ROOT.as_posix())
    return data


def _skill_entry(path: Path, repo_root: Path) -> dict[str, str]:
    meta, title = _parse_skill(path.read_text(encoding="utf-8"))
    name = meta.get("name") or path.parent.name
    description = meta.get("description") or ""
    return {
        "name": name,
        "description": description,
        "title": title or name,
        "path": _relative_posix(path, repo_root),
        "directory": _relative_posix(path.parent, repo_root),
    }


def _parse_skill(text: str) -> tuple[dict[str, str], str]:
    meta: dict[str, str] = {}
    body = text
    if text.startswith("---\n"):
        end = text.find("\n---", 4)
        if end != -1:
            frontmatter = text[4:end].strip()
            body = text[end + 4 :]
            for line in frontmatter.splitlines():
                if ":" not in line:
                    continue
                key, value = line.split(":", 1)
                meta[key.strip()] = value.strip().strip("\"'")

    title = ""
    for line in body.splitlines():
        if line.startswith("# "):
            title = line[2:].strip()
            break
    return meta, title


def _relative_posix(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def _score_skill(skill: dict[str, Any], query: str, query_tokens: set[str]) -> int:
    name = str(skill.get("name", "")).lower()
    description = str(skill.get("description", "")).lower()
    title = str(skill.get("title", "")).lower()
    haystack = f"{name} {title} {description}"
    haystack_tokens = _tokens(haystack)

    score = len(query_tokens & haystack_tokens)
    query_lower = str(query).lower()
    if name and name in query_lower:
        score += 5
    for token in query_tokens:
        if token and token in name:
            score += 2
        elif token and token in description:
            score += 1
    return score


def _tokens(text: str) -> set[str]:
    return {
        token
        for token in re.findall(r"[a-zA-Z0-9][a-zA-Z0-9_-]*", text.lower())
        if len(token) > 2
    }


def _registry_markdown(registry: dict[str, Any]) -> str:
    lines = [
        "# Project Skill Registry",
        "",
        "Generated by `co-math refresh-skills` from project-local skills.",
        "",
        f"- skill_root: `{registry.get('skill_root', SKILL_ROOT.as_posix())}`",
        f"- generated_at: `{registry.get('generated_at', '')}`",
        "",
        "## Skills",
        "",
    ]
    skills = registry.get("skills", [])
    if not skills:
        lines.append("No project-local skills were found.")
    for skill in skills:
        lines.extend(
            [
                f"### {skill.get('name', '')}",
                "",
                f"- path: `{skill.get('path', '')}`",
                f"- description: {skill.get('description', '')}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"
